name: speech-meg
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - arrow-cpp=11.0.0
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - audioread=3.0.1
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - cycler=0.12.1
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.6.7
  - dill=0.3.7
  - edflib-python=1.0.8
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - frozenlist=1.4.1
  - ftfy=6.1.1
  - future=0.18.3
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - langcodes=3.3.0
  - lazy_loader=0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcurl=8.4.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libidn2=2.3.4
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - librosa=0.10.1
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - lightning-utilities=0.10.0
  - llvm-openmp=17.0.4
  - llvmlite=0.41.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mne-base=1.5.1
  - mne-bids=0.13
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.3
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - multidict=6.0.4
  - multiprocess=0.70.14
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - networkx=2.8.8
  - nibabel=5.2.0
  - ninja=1.11.1
  - nspr=4.35
  - nss=3.89.1
  - numba=0.58.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=3.2.1
  - orc=1.7.4
  - packaging=23.2
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=4.0.0
  - ply=3.11
  - pooch=1.8.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow-hotfix=0.6
  - pybv=0.7.5
  - pycparser=2.21
  - pygments=2.16.1
  - pymatreader=0.0.32
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.4.1
  - python_abi=3.9
  - pytorch-lightning=2.1.3
  - pytorch-model-summary=0.1.1
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - responses=0.18.0
  - sacremoses=master
  - safetensors=0.3.3
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - soxr=0.1.3
  - soxr-python=0.3.7
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - tokenizers=0.15.0
  - tomli=2.0.1
  - torchmetrics=1.2.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - transformers=4.36.2
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.1.0
  - utf8proc=2.6.1
  - wcwidth=0.2.10
  - wheel=0.41.3
  - wordfreq=2.5.1
  - x264=1!157.20191217
  - xmltodict=0.13.0
  - xxhash=0.8.2
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.28.0
      - altair==5.3.0
      - annexremote==1.6.4
      - antlr4-python3-runtime==4.8
      - appdirs==1.4.4
      - audiolm-pytorch==2.0.7
      - beartype==0.18.2
      - bitarray==2.9.2
      - blinker==1.8.2
      - boto==2.49.0
      - cachetools==5.3.3
      - chardet==5.2.0
      - cryptography==42.0.2
      - cython==3.0.10
      - datalad==0.19.6
      - datasets==2.19.0
      - decorator==4.4.2
      - diffusers==0.27.2
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - einx==0.2.0
      - ema-pytorch==0.4.5
      - encodec==0.1.1
      - fairseq==0.12.2
      - fasteners==0.19
      - fracridge==2.0
      - frozendict==2.4.2
      - fsspec==2023.9.2
      - gateloop-transformer==0.2.4
      - gitdb==4.0.11
      - gitpython==3.1.41
      - glmsingle==1.2
      - himalaya==0.4.6
      - huggingface-hub==0.22.2
      - humanize==4.9.0
      - hydra-core==1.0.7
      - image-similarity-measures==0.3.6
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - iso8601==2.1.0
      - jaraco-classes==3.3.1
      - jeepney==0.8.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - keyring==24.3.0
      - keyrings-alt==5.0.0
      - lion-pytorch==0.1.4
      - local-attention==1.9.0
      - looseversion==1.3.0
      - lxml==5.1.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - moviepy==1.0.3
      - musiclm-pytorch==0.2.8
      - mutagen==1.47.0
      - nilearn==0.10.3
      - nltools==0.5.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.0.6
      - open-clip-torch==2.24.0
      - opencv-python==4.9.0.80
      - pandas==2.2.2
      - patool==1.15.0
      - patsy==0.5.6
      - phasepack==1.5
      - portalocker==2.8.2
      - proglog==0.1.10
      - pyarrow==15.0.2
      - pycryptodomex==3.20.0
      - pydeck==0.9.1
      - pynv==0.3
      - python-gitlab==4.4.0
      - pytorch-warmup==0.1.1
      - pywavelets==1.5.0
      - referencing==0.35.1
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rotary-embedding-torch==0.5.3
      - rpds-py==0.19.0
      - sacrebleu==2.4.2
      - scikit-image==0.20.0
      - scipy==1.9.1
      - secretstorage==3.3.3
      - sentencepiece==0.2.0
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - setuptools-scm==8.0.4
      - smmap==5.0.1
      - statsmodels==0.14.2
      - streamlit==1.36.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tifffile==2024.2.12
      - timm==0.9.16
      - toml==0.10.2
      - toolz==0.12.1
      - torch==2.1.2
      - torch-stft==0.1.4
      - torchaudio==2.1.2
      - torchsummary==1.5.1
      - torchvision==0.16.2
      - triton==2.1.0
      - vector-quantize-pytorch==1.14.7
      - wandb==0.16.2
      - watchdog==4.0.1
      - websockets==12.0
      - x-clip==0.14.4
      - yt-dlp==2024.4.9
